//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsPolySongJalon3.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsPolySongJalon3.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Attribution_covoiturage {
            get {
                object obj = ResourceManager.GetObject("Attribution_covoiturage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Auto_Stop_32 {
            get {
                object obj = ResourceManager.GetObject("Auto_Stop_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cascade_display {
            get {
                object obj = ResourceManager.GetObject("cascade_display", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap covoiturage_32 {
            get {
                object obj = ResourceManager.GetObject("covoiturage_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur d&apos;insertion.
        /// </summary>
        internal static string COVOITURAGE_INS_ERR {
            get {
                return ResourceManager.GetString("COVOITURAGE_INS_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_a_propos_de_nous_homme_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_a_propos_de_nous_homme_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_chorale_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_chorale_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_déconnexion_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_déconnexion_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_exporter_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_exporter_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_fichier_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_fichier_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_Mosaic {
            get {
                object obj = ResourceManager.GetObject("icons8_Mosaic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_sortie_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_sortie_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_utilisateur_32 {
            get {
                object obj = ResourceManager.GetObject("icons8_utilisateur_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newlogoPSg {
            get {
                object obj = ResourceManager.GetObject("newlogoPSg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur d&apos;insertion.
        /// </summary>
        internal static string PROPOSE_INS_ERR {
            get {
                return ResourceManager.GetString("PROPOSE_INS_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur d&apos;insertion du  chauffeur &apos;{0} {1}&apos; dans la table des covoiturages..
        /// </summary>
        internal static string TEXT_INSCOVOITURAGE_ERR {
            get {
                return ResourceManager.GetString("TEXT_INSCOVOITURAGE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur d&apos;insertion du  chauffeur &apos;{0} {1}&apos; dans la table propose..
        /// </summary>
        internal static string TEXT_INSPROPOSE_ERR {
            get {
                return ResourceManager.GetString("TEXT_INSPROPOSE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attribution.
        /// </summary>
        internal static string TITRE_ASSIGNMENT {
            get {
                return ResourceManager.GetString("TITRE_ASSIGNMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de places atteintes.
        /// </summary>
        internal static string TITRE_ERRADDCOVOIT {
            get {
                return ResourceManager.GetString("TITRE_ERRADDCOVOIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de création.
        /// </summary>
        internal static string TITRE_ERRADDUTIL {
            get {
                return ResourceManager.GetString("TITRE_ERRADDUTIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attention doublon.
        /// </summary>
        internal static string TITRE_ERRDOUBL {
            get {
                return ResourceManager.GetString("TITRE_ERRDOUBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de modification.
        /// </summary>
        internal static string TITRE_ERRMODIF {
            get {
                return ResourceManager.GetString("TITRE_ERRMODIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de supression.
        /// </summary>
        internal static string TITRE_ERRSUPP {
            get {
                return ResourceManager.GetString("TITRE_ERRSUPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer &apos;{0} {1}&apos;.
        /// </summary>
        internal static string TITRE_SUPP {
            get {
                return ResourceManager.GetString("TITRE_SUPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur sur la base de données..
        /// </summary>
        internal static string TITREERRMYSQL {
            get {
                return ResourceManager.GetString("TITREERRMYSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attribution pour l&apos;avtivité &apos;{0}&apos; effectuée..
        /// </summary>
        internal static string TXT_ASSIGNEMENT {
            get {
                return ResourceManager.GetString("TXT_ASSIGNEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;ajout du covoitureur n&apos;a pas été réalisé..
        /// </summary>
        internal static string TXT_ERRADDCOVOIT {
            get {
                return ResourceManager.GetString("TXT_ERRADDCOVOIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;ajout de l&apos;utilisateur n&apos;a pas été réalisé..
        /// </summary>
        internal static string TXT_ERRADDUTIL {
            get {
                return ResourceManager.GetString("TXT_ERRADDUTIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;utilisateur &apos;{0} {1}&apos; existe dèja !.
        /// </summary>
        internal static string TXT_ERRDOUBL {
            get {
                return ResourceManager.GetString("TXT_ERRDOUBL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La modification n&apos;a pas été réalisée..
        /// </summary>
        internal static string TXT_ERRMODIF {
            get {
                return ResourceManager.GetString("TXT_ERRMODIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue, veuillez vérifier votre connexion..
        /// </summary>
        internal static string TXT_ERRMYSQL {
            get {
                return ResourceManager.GetString("TXT_ERRMYSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La suppression n&apos;a pas été réalisée..
        /// </summary>
        internal static string TXT_ERRSUPP {
            get {
                return ResourceManager.GetString("TXT_ERRSUPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez vous supprimer la ligne sélectionnée ?.
        /// </summary>
        internal static string TXT_SUPP {
            get {
                return ResourceManager.GetString("TXT_SUPP", resourceCulture);
            }
        }
    }
}
